version: 0.2

phases:
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd

artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml
    - beforeInstall.sh
    - deploy.sh
  discard-paths: yes
cache:
  paths:
    - '/root/.gradle/caches/**/*'
